### ISSUE TITLE
WebVR demo doesn't work with the latest version of the spec

### ISSUE THREAD

**Issue by IanET** [google/marzipano#103]
Tried the WebVR demo with Edge (on an Acer HMD) and it shows "No VR Device Detected". Other WebVR demos seem to work OK so it doesn't seem like a generic Edge issue.

**Comment by tjgq** [comment]
The WebVR spec is in flux, and the demo hasn't been updated in a while. However, it looks like the `getVRDevices` API has been replaced with `getVRDisplays` in the most recent spec.

Can you try changing that in the demo and see if it works? Unfortunately, I can't do it myself because I don't have access to a VR device running Edge. I've tried the demo in a Google Pixel and it works (possibly because the older API is still supported).

Feel free to send a pull request if you manage to fix it!

**Comment by tjgq** [comment]
I've updated the WebVR demo to work with the latest spec, and tested it on a Google Cardboard. Note that the demo on http://www.marzipano.net is still the old version; only the GitHub master branch is up to date.

Please reopen if it still doesn't work with other WebVR displays.
