### ISSUE TITLE
tiles proactive preload

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#116]
Would it be possible to force-preload specific tiles of a scene at a certain level to have a reliable "zoom in" effect just a few moments after the scene is loaded? 
The usage scenario would be something like quickly decreasing FOV in say, 2 seconds after a user clicks a specifically formed link to zoom in to a defined hotspot.
The idea is to make the viewer.lookTo experience as smooth as possible.

**Comment by tjgq** [comment]
You can sort of do this with `TextureStore#pin` and `TextureStore#unpin` - the main issue is deciding when to unpin, since you probably don't want your prefetched textures to stick around forever (maybe unpin after a fixed timeout?).

One thing to keep in mind is that textures are loaded in order, and there's no way to jump the queue. So if you pin some textures, then the view moves in another direction and the TextureStore tries to pull in some other textures, the latter will only start loading after the pinned ones (unless you unpin them, which aborts loading).

**Comment by jordyno** [comment]
Good idea! Maybe I could just call the TextureStore#unpin with the lookTo loadComplete event or add extra seconds thereafter.
The other issue is how to figure out which tiles are to be pinned around a specific hotspot?

**Comment by tjgq** [comment]
There is a way, but it relies on the  undocumented method `CubeGeometry#_closestTile` (which perhaps should be made part of the official API). It will give you the closest tile to a given (yaw, pitch) at a given level. Then you can call `CubeTile#neighbors`, `CubeTile#parent` and `CubeTile#children` to find more tiles around it.

**Comment by jordyno** [comment]
Wow that's quite awesome! Might pretty much solve this issue, thank you!
Keeping this open in case you plan to make CubeGeometry#_closestTile part of official API.
