### ISSUE TITLE
How to install and run marzipano locally on my computer?

### ISSUE THREAD

**Issue by ObfuscateTheWeb** [google/marzipano#132]
I've read the documentation but I still don't really know what to do. I'm sure many marzipano users want the same thing, I've asked this question on the google discussions board, but there are no replies there so I'm asking it here on github.

The question is simple: how do I make a working marzipano tool from the source code myself and have it run locally offline on my computer? It should be the same marzipano tool on the website, but run locally on my computer, has anyone done this before and can give me guidance?

I really appreciate any help, and thank you developers for making such an amazing tool (it's probably the best out there)

EDIT: I downloaded a zip of the source, but when I open the folder, I expected to find a .html file that will open with a working marzipano tool, but I was wrong, there's no such thing

**Comment by tjgq** [comment]
The Marzipano Tool isn't part of the open source project (and we don't have plans to release it). So the answer is that you cannot. Sorry.

**Comment by ObfuscateTheWeb** [comment]
Ok, so the tool itself is closed source. So what is the documentation for? If I do all the instructions there correctly, what do I get? Do I get a marzipano tool or? Sorry if I don't understand, mind explaining a little?

**Comment by tjgq** [comment]
The thing we call Marzipano is a Javascript library for displaying 360 panoramas in the browser. The library is fully open source and you can find it, along with some demos, in this GitHub repository.

The page at [http://www.marzipano.net/docs.html](http://www.marzipano.net/docs.html) is documentation for the library. It is written for programmers who want to use it in their projects. You would follow them to code a virtual tour from scratch, rather than using the Marzipano Tool.

The Marzipano Tool is a web application, available at [http://www.marzipano.net/tool](http://www.marzipano.net/tool), written around the Marzipano library. It allows someone without programming knowledge to assemble a virtual tour from a set of 360 panoramas. But the tool itself is not open source.

When you export a tour from the tool, you get a zip archive with some HTML, CSS and Javascript files. One of those files is the Marzipano library, and the others implement the functionality and visual look of the tour.

You can upload the files into a web hosting service to make the tour available for other people to see. You can also make changes to the files to further customize the tour, but that requires some knowledge of Javascript and/or CSS.

**Comment by ObfuscateTheWeb** [comment]
Well, thank you for the nice explanation, but problem is, the documentation looks kinda complicated, is there an active forum where I can get step-by-step instructions to set everything up? It's difficult, but I'm willing to try, where do I get help from people?

**Comment by tjgq** [comment]
Can you first explain what you're trying to do?

**Comment by ObfuscateTheWeb** [comment]
Documentation is lacking steps in my opinion, or maybe I'm just too noob. What i'm looking for is step-by-step instructions to end up with a working virtual tour.

**Comment by tjgq** [comment]
Why is the Marzipano Tool not enough for your purposes? Even if you want to customize the look of the tour, taking a generated tour as the starting point will be a lot less work (you might be able to make your changes on the CSS and not have to modify the Javascript at all, for example).

If your objective is to fully understand how everything fits together, I would encourage you to begin by studying the source code for one of the simpler demos - [this one](https://github.com/google/marzipano/tree/master/demos/cube-single-res), for example. It's not a full tour, but the code is simple enough that you can follow along by referring to the documentation. The documentation does expect you to have some prior knowledge about web development.

Our [discussion forum](https://groups.google.com/forum/#!forum/marzipano) is the right place to ask questions about the library. Please feel free to post there, but note that we can only help with Marzipano-specific issues, not general web development questions (there are better forums/tutorials for that elsewhere on the Internet).

**Comment by ObfuscateTheWeb** [comment]
Thank you for help sir, I'll study and hope to understand it. Meanwhile, I could only hope the website stays alive for as long as possible :)

**Comment by tocan** [comment]
Hi, i like to stop here and ask for something similar. I guess he wish to provide an own service in the net to have more vistors to his webpage.

I like to speak open. Did fork marzipano for a maybe later use. My problem is i search a fast working solution for my river boat tour through europe for carthography. I plan to do each 50 m to make a photo from the river with gps tags and like to put the results to openstreetmap. 

Means 3000 km and often no internet on the river. So each photo is gps tagged for position. and very often background text information and notices. Each day will be arround 20-80 km and to work out in night with posting to online tool will not be the best solution.

Any idea? All photos and the tour should be cc-by-sa compatible. If marcipano is not the best tool for this maybe you can point me to another solution. Because of 12 volts electricity most should be possible with a tablet. Board pc is in general raspberry pi.

**Comment by coreymcd37** [comment]
@tocan I can help you with your project.  Please contact me at Coreymcdaniel@me.com

**Comment by qnaqbgss** [comment]
Friend Please help me, I can't run marzipano locally on my computer too.
Can you send me the complete demo about "Video",URL:"http://www.marzipano.net/demos/video-multi-res",thanks

**Comment by qnaqbgss** [comment]
my email  317802776@qq.com

**Comment by NoTele-lu** [comment]
Hey there...

So I've been looking around for Open Source 360 Virtual Tour Software Solutions which are easy to deploy and to handle by non used users. So this is when I landed on your Marzipano Tool which honestly is one of the best an simplest tools I stumbled on! Thanks for that!

My major problem is that I need an offline solution like that! I need solutions which are working under circumstances where connectivity is an issue (example: disaster & emergency situations) and where we are not being able to have a permanent internet connection or that the speed is that low that you can not waste it for "unimportant" data like that... Has anybody an idea or an alternative? Because the server solution is an ideal approach! You don't have to install the software on all computers because often these devices change but still are able to keep it updated and available in the small internal net.

Or does anybody know if the statement of non disclosing the code does still apply? Or has anybody programmed a similar tool? Because that's my problem. The server itself is good but only half of the solution...

Thanks in advance for any help!

**Comment by RonBulaon** [comment]
> The Marzipano Tool is a web application, available at http://www.marzipano.net/tool, written around the Marzipano library. It allows someone without programming knowledge to assemble a virtual tour from a set of 360 panoramas. But the tool itself is not open source.


I understand that the Marzipano Tool  is not opensource, but do you have a paid version somewhere?
