### ISSUE TITLE
Feature request: explicitly warn end user about unsupported fov

### ISSUE THREAD

**Issue by etki** [google/marzipano#136]
Hi!
This is purely better-developer-experience request without any real functional changes. Currently developer may accidentally tune FOV to an unsupported value (e.g. more than one PI), and Marzipano won't render anything (which is totally as it should behave with such FOV, but it is not clear why). I believe, it would be quite appropriate to throw a warning into console in such case.

**Comment by tjgq** [comment]
This might be a bug. Even if there's no view limiter, the fov should never exceed π; when you set a larger value it gets truncated (see the code [here](https://github.com/google/marzipano/blob/master/src/views/Rectilinear.js#L496)). Extreme distortion is to be expected - that's what a fov close to π does.

If it actually crashes, or appears not to react to the controls, or it gets into a state that you can't get out of anymore, that's a bug. Do you have a minimal example that we can take a look at?

**Comment by etki** [comment]
@tjgq this happened when my custom limiter was setting fov to values > 2 PI, and only after i've zoomed in i've started to see distortions, then the regular pano (as soon as field of view got to regular values). My guess is that a cubemap with fov === Math.PI is rendered completely blank, and until it is moved and/or zoomed it stays in same condition. Here's the fiddle, but i guess it may work or not depending on mixed content security and iframe size:

https://jsfiddle.net/tcen0t2w/4/

on my machine it renders completely blank, but content starts to appear as soon as i zoom in

**Comment by tjgq** [comment]
I see what you mean. On my machine it renders either the full view or only parts of it (the rest remains blank) depending on the view angle.

The fundamental problem here is that setting fov to exactly π can't possibly work, because the projection is mathematically undefined. In practice, due to the precision limitations of WebGL, it stops working when you get too close to π.

When I said we truncate the fov to π, that's not actually true: we truncate to π - ε, where ε is a very small number (currently it's 1e-9). This should let users get as close to π as possible without breaking the rendering, but as your example demonstrates, in some cases it's not enough. So we should pick a more conservative value for ε (I'll do that once I've had the opportunity to test on more machines).
