### ISSUE TITLE
blendFunc for anaglyph layers not working

### ISSUE THREAD

**Issue by jmiba** [google/marzipano#149]
It only does if you change t.blendFunc(t.ONE,t.ONE_MINUS_SRC_ALPHA) to t.blendFunc(1,1,1,1,1,1,1,1) in marzipano.js.

**Comment by tjgq** [comment]
Thanks for noticing this! The anaglyph demo did in fact require a custom blend function to be set, but we removed that option in the latest release.

It turns out that the anaglyph effect can also be produced with the default (ONE, ONE_MINUS_SRC_ALPHA) blend function, as long as you use a suitable color transform.
In a nutshell, the image rendered on top should have zero alpha, so that the ONE_MINUS_SRC_ALPHA factor becomes just ONE. I've updated the source code for the demo and the Marzipano website to demonstrate this.

**Comment by jmiba** [comment]
Thank you, that solved it. I adjusted the code in my project.
