### ISSUE TITLE
Using a second [standard] screen next to Mac Retina -- odd behavior

### ISSUE THREAD

**Issue by benungs** [google/marzipano#196]
This uses a basic 360 marzipano webpage, generated with the Marzipano tool, unmodified afterwards. Initial image resolution: 16,384 x 8192 JPG

On a setup with a 5K Retina iMac, with an additional non-retina monitor attached, the zoom display of the image is different:
![marzipanoon5k](https://user-images.githubusercontent.com/25394210/47528997-d9120980-d863-11e8-89bc-0de0b4a405e2.jpg)
(_Standard on left, Retina on right_)
Both of these are zoomed in at max value, but the retina screen is significantly smaller. 

The real bugginess, however, is revealed when dragging a window across screens. 

SITUATION 1:  Retina to Non-Retina
At first, the image looks the same as the retina-screen image above after dragging the window over. Once you click-drag the image, however, it shrinks to approximately one-half size to the lower-left corner of the window:
![retinabug2](https://user-images.githubusercontent.com/25394210/47529261-8ab13a80-d864-11e8-9a2b-dcc237f0f7b1.jpg)
(_a view of the non-retina monitor, after the web page has been dragged from the retina monitor and a slight click-drag has engaged on the image_)
The optical center of the view is in the middle of this small image. Simply refreshing the page restores it to the correct state.

SITUATION 2: Non-Retina to Retina
When dragging a window the other direction (after you've refreshed the web page on a standard screen), it again appears the same as it did on the non-retina screen (as shown in the top image). Once you click-drag, however, the image increases in size by [I'm guessing] a factor of 2, scaling from the lower-left corner:
![retinabug3](https://user-images.githubusercontent.com/25394210/47529631-94876d80-d865-11e8-8be2-1633725e4bd5.jpg)
(_after dragging the initial view from a non-retina to retina screen_)
This time, the optical center of the view is to the upper right, well off the visible part of the screen. It's very awkward and confusing if you aren't expecting it. Again, a simple refresh fixes the content.

**Comment by benungs** [comment]
I forgot to mention: This is a simple 360 view, generated with the Marzipano tool, unmodified afterwards. Initial image resolution: 16,384 x 8192 JPG

**Comment by tjgq** [comment]
The first case (zoom level on retina != zoom level on non-retina) is because the device pixel ratio is taken into account when deciding which zoom level to use. In other words, the retina monitor has a larger (physical) resolution, so it fits more of the panorama at the same zoom level.

The second case (broken rendering when dragging window into a different screen) is likely because we _don't_ update the view to match the pixel ratio when the window is dragged across screens (it's only updated when a window resize event fires, but no resize happens when moving to the other screen, since CSS pixels are device-independent). So the viewport calculations are off.

A call to `Viewer#updateSize` would probably fix the rendering, but there's no way to do it automatically (short of polling) as there's no browser API to detect that the pixel ratio changed.

**Comment by tjgq** [comment]
The other viewers either:

a) don't scale the view according to the device pixel ratio (i.e., retina monitors use effective resolution instead of physical resolution);

b) Poll for the device pixel ratio in a loop to detect changes.

I suspect they all do a). I wouldn't be totally opposed to changing the default behavior of Marzipano here (perhaps together with an API to revert to the old behavior). In fact, the current behavior seems to be a bad choice precisely because of this bug.

**Comment by tjgq** [comment]
The scaling issues when switching screens should have been fixed in the latest release (v8.0.0) and in the Marzipano Tool.

To avoid having to recreate the tour, you can get the latest `marzipano.js` from the website and replace the file of the same name in an already generated tour.
