### ISSUE TITLE
renderComplete per layer

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#200]
Currently, the `stage#renderComplete`  fires as soon all of the layers are rendered stable. Would be practical to have a similar event fired as per layer, something like `layer#renderComplete`. For example, in a multilayer scenario with semitransparent layers it makes sense to have such event to display layers as they become available/loaded.
What would be the best way to implement this?

**Comment by tjgq** [comment]
It would be straightforward to modify `Stage#renderComplete` to return an array of booleans (where the i-th element indicates whether the i-th layer is stable). Search for the `stableStage` and `stableLayer` variables inside the `Stage#render` method.

**Comment by tjgq** [comment]
To answer the larger question, a `Layer` doesn't have enough information to know whether it has been stably rendered, so it's not possible to add a `Layer#renderComplete` event unless `Stage` shares additional information with `Layer` (which I'd prefer to avoid, as `Layer` is by design an immutable data structure).

**Comment by tjgq** [comment]
After pondering about this, I actually like the "Stage emits event on behalf of Layer" solution better than the alternatives, so there you have it - you can listen for `Layer#renderComplete` now.

It would also make sense to add `Scene#renderComplete`, but that takes a bit more work.

**Comment by jordyno** [comment]
Thank you @tjgq  ! This really helps!
