### ISSUE TITLE
Feature request: dynamically handled "initialViewParameters"

### ISSUE THREAD

**Issue by WCD-YB** [google/marzipano#218]
@tjgq: First of all, thanks for this great framework!
I have a probably simple concern. 
Currently, an "initialViewParameters" is defined in the data.js for each individual image.
Therefore, my question is: 
Is it possible to set this parameter only for the first "landing" image and use the last viewing angle from the current hotspot as the initial angle when forwarding to other hotspots? 
This behavior would increase immersion and behave in a similar way to google streetmaps. 
I know that the individual images must have the same orientation, but in my case this can be well taken into account when recording.

Thanks a lot!

**Comment by tjgq** [comment]
Each scene has a separate view instance, so when you move around in a scene, the view for the other scenes isn't updated automatically. You can achieve what you want by listening for the `sceneChange` Viewer event, and copying the view yaw parameter from the old scene (the one being switched from) to the new one (the one being switched to).

Alternatively, you could change the code so that all scenes share a single view instance.

**Comment by WCD-YB** [comment]
Thank you for your help! I've added the old scene as a Parameter and scene.view.setPitch(...) as well as scene.view.setYaw(...) to the switchScene() function in index.js. It works very well! Thx tjgq

**Comment by mpvlc** [comment]
Hi there ! I'm JS beginner, I would like to solve this issue view initial view parameters.
Guys is it possible to show me the whole code, what am I supposed to rewrite and where.. I trying to solve this couple weeks and still no success :/
Thank you very much
