### ISSUE TITLE
device orientation button showing on desktop

### ISSUE THREAD

**Issue by vanKaam** [google/marzipano#244]
device orientation button showing on desktop which it off course shouldn't if the function is connected to a gyro.

**Comment by jordyno** [comment]
there are desktop devices which do have a gyro, the surface line for instance

**Comment by tjgq** [comment]
Are you referring to this demo? http://www.marzipano.net/demos/device-orientation/index.html

The code just assumes that device orientation is available, it doesn't actually check (which is ok for a demo).

As a side note, the demo stopped working on the latest Chrome because device orientation events are no longer available on plain HTTP. I intend to move the www.marzipano.net website to HTTPS so that it works again.
