### ISSUE TITLE
Warning on Chrome [latest] - Added non-passive event listener to a scroll-blocking 'wheel' event

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#250]
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. 
This points to ElementPressControlMethod.

Would this contribute to better performance if we fix this?

**Comment by tjgq** [comment]
I think this is in `ScrollZoomControlMethod`, which is the only control method that listens to mouse wheel events. 

I suspect we can't use a passive listener because we also call `preventDefault` [here](https://github.com/google/marzipano/blob/6e587b4af2e414599b57b1d005672c84238d9d70/src/controls/ScrollZoom.js#L98), and `preventDefault` doesn't work for passive listeners.

**Comment by mrlubos** [comment]
@tjgq Why does Marzipano need to call [`e.preventDefault();`](https://github.com/google/marzipano/blob/6e587b4af2e414599b57b1d005672c84238d9d70/src/controls/ScrollZoom.js#L98)?

**Comment by tjgq** [comment]
It's probably to prevent scrolling the whole page, if you're embedding the viewer in a non-fullscreen scenario.
