### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by devbhagat2003** [google/marzipano#26]
Hi, 
I am not able to compile it. 
npm install does create respective npm-modules, but give error at chokidar/fsevents
https://gyazo.com/5ed5f100219499b24c1c63440cfc7cd0

after that when you do npm run dev : it does not work
These are the error which you come across:

npm ERR! Failed at the marzipano@0.5.1 dev script 'scripts/dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marzipano package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marzipano
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marzipano
npm ERR! There is likely additional logging output above.

Thanks.

**Comment by mitarbeiterDesMonats** [comment]
Same error here, but far more relevant than the skipped optional dependencies should be the deprecated-errors from the top of the console-log when you run "npm install":

$ npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> flex-sdk@4.6.0-0 preinstall /home/samuel/ogulo/alpha/marzipano/node_modules/.staging/flex-sdk-809ebfc4
> npm install playerglobal-latest

npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by manuelcabral** [comment]
In which system is `npm run dev` not working? In Linux I am also getting the chokidar/fsevents warning, which seems to be coming from watchify, but `npm run dev` runs after that.

Most of the deprecated warnings seem to be coming from dependencies. I will check if any of them can be updated.

**Comment by mitarbeiterDesMonats** [comment]
In my case `npm run dev` fails on Arch Linux.

**Comment by gibbitz** [comment]
I see the warnings as well, but what stops my build is at the top of my output:

`fatal: Not a git repository (or any of the parent directories): .git
{ [Error: Command failed: git describe --tags HEAD
fatal: Not a git repository (or any of the parent directories): .git
]`

I included the project via NPM (using my package.json dependencies) and the build script seems to be trying to pull from git (which had nothing to do with how the code got there) to update (which should be controlled by package.json, not the build code). This wouldn't be an issue if the built code were either part of the repository or built by a postinstall script (that didn't involve pulling the code from git when the source came from npm). It looks like the way around this is going to be to pull the built code from the website and put it in my source code repo, then shim it with browserify because I have little control beyond package.json in my continuous integration environment. </soapbox>

Are you guys seeing this message at the top as well or do I need to file a separate bug?

**Comment by tjgq** [comment]
The build script isn't supposed to run if you're just `require`ing the module in a Browserify environment. What is causing the build script to run?

**Comment by gibbitz** [comment]
There's no build folder or marzipan.js file using `npm i` with package.json. I was viewing the demos via nginx and could see `build/marzipan.js` was returning 404. So I tried running dev and build manually in order to vivisect the demos. I see now that in your package.json, main is pointing to `src/index.js`, so it looks like my CI won't have issues (thankfully). I just pulled down the compiled file (zip) from the site to get the demos running. I wasn't expecting the build to not work from npm though. May be worth making a change to the npm repo to allow that to work, include the built code in the demos (so fools like me wouldn't be tempted to try), or note that builds will only work when the code is cloned from the git repo in the README...

**Comment by tjgq** [comment]
Ah, that explains it. The dev/build scripts are meant to be used by developers, not regular users. The fact that the demos don't work out of a fresh git clone / npm install is definitely less than ideal, but it's a compromise to avoid checking compilation products into the repository. I'll try to spell it out more clearly in the README.
