### ISSUE TITLE
[Question] Blank space using React

### ISSUE THREAD

**Issue by PironSteve** [google/marzipano#281]
Hi, I'm trying to use Marzipano with react but I can't show my picture, there is a blank space instead with a canva at height 0.

There is something special to do with React to make it fonctionnal ?

**Comment by tjgq** [comment]
You need to ensure that the viewer DOM element has its dimensions set in CSS, e.g. `width: 100%; height: 100%` to fill the entire parent element. You may want to compare with the CSS on one of the demos.

I don't know anything about React, so if this turns out to be something React-specific (and not just a general CSS issue), you may have better luck by posting on a React forum or mailing list.
