### ISSUE TITLE
scene switch lags opacity transition animation

### ISSUE THREAD

**Issue by un0btanium** [google/marzipano#299]
I noticed that when I have `pinFirstLevel: false` that the panorama image I switch to is loaded while the transition occurs. The loading process of the image is causing the webpage to freeze, interrupting the transition. Once the image is loaded the transition is trying to catch up, making the transition seem almost complete instantly and looking very unsmooth and buggy.

The same problem exists when I add a low resolution preview and a high resolution level (and put pinFirstLevel to true). Then the preview images are loaded on startup and the high resolution image is loaded lagging the transition to the scene.

I am currently using equirectangular panorama image. Would this be the cause because the images are large ones and need to be loaded in its entirety? I feel like this issue is related to [this one](https://github.com/google/marzipano/issues/226). Would using cube maps instead fix the issue for good?

**Comment by tjgq** [comment]
Maybe. Large equirectangular images result in a suboptimal rendering experience because they can't be loaded in small pieces. I would generally recommend using cubemaps.

There is also an open [PR](https://github.com/google/marzipano/pull/298) to do the image loading off-thread, which might help here.

**Comment by un0btanium** [comment]
Is there a tool you would recommend for splitting a equirectangular image into cubemaps (idealy one that already generates different, customizable tile grid sizes and levels of details and outputs them in seperate folders)?

Interesting that we are getting threading in the browser. Cant wait till that is officially merged and working for more browsers.

**Comment by campmdabt** [comment]
I use krpano's cli to create tiles from equirectangular photos and then use
marzipano to display them. It's a paid product but very good.

I initially used the viewer for krpano as well and while was very happy
with the author and community support as a whole, I despise the xml based
custom coding language it uses instead of Javascript like marzipano.

You pay for a license for both pieces, but I only use it to create the
tiles.

**Comment by tjgq** [comment]
The krpano tools definitely work; [Hugin](http://hugin.sourceforge.net/) is a free (open source) alternative.

**Comment by un0btanium** [comment]
Someone knows how the Marzipano Editor Tool does it?

**Comment by campmdabt** [comment]
Looks like it pulls down https://www.marzipano.net/tool/js/equirect.worker.js to do the work, but neither the ../LICENSES.txt file it references nor the code itself betrays what it's using.
