### ISSUE TITLE
parameterDynamics event is not triggered when view is finishing easing

### ISSUE THREAD

**Issue by b-strauss** [google/marzipano#313]
As far as I can tell the `parameterDynamics` event is the only event to detect changes in view params.

Unfortunately this event is not triggered when the view is still easing to it's end position after a mouse move.

See this log of events:

![image](https://user-images.githubusercontent.com/6588177/80827254-eee45580-8be3-11ea-9ccf-f216272c738f.png)

The first stream of events comes directly from dragging the view with the mouse.
`mouse up` is fired when the user finishes dragging, I added this event to log the position at that time.
After a delay of 1 second the current position is again logged.

I expected there to also be a stream of events being fired between when the user stops dragging and the viewer reaching the endposition. But there is a large gap of events in between these moments.

Is there any way to listen for changes in this timeframe?

**Comment by campmdabt** [comment]
You should be able to use the change event for the applicable View in order
to see when the view changes:
https://www.marzipano.net/reference/View.html#event:change



Create a viewer:

viewer = new Marzipano.Viewer(panoDivElement, {

        // controls: tourObj.settings,

        stage: {

            antialias: true,

            generateMipmaps: true

        }

    });



Then add your handler:

viewer.addEventListener('viewChange', eventHandler);





[image: Logo] <http://cdn.atlasbayvr.com/img/mailicon.gif>

*Cameron Abt*
Chief Executive Officer
Atlas Bay VR *|* Virtual Reality for Real Estate
3423 Piedmont Rd NE *|* Atlanta, GA *|* 30305
*m.* (617) 470-7727 *| o.* (404) 585-8837
*cameron.abt@atlasbayvr.com <cameron.abt@atlasbayvr.com>* *| *atlasbayvr.com
<https://www.atlasbayvr.com/?utm_source=email&utm_campaign=signature&utm_medium=email&utm_content=cameron>





*From:* Benjamin Strauß <notifications@github.com>
*Sent:* Friday, May 1, 2020 1:50 PM
*To:* google/marzipano <marzipano@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* [google/marzipano] parameterDynamics event is not triggered when
view is finishing easing (#313)



As far as I can tell the parameterDynamics event is the only event to
detect changes in view params.

Unfortunately this event is not triggered when the view is still easing to
it's end position after a mouse move.

See this log of events:

[image: image]
<https://user-images.githubusercontent.com/6588177/80827254-eee45580-8be3-11ea-9ccf-f216272c738f.png>

The first stream of events comes directly from dragging the view with the
mouse.
mouse up is fired when the user finishes dragging, I added this event to
log the position at that time.
After a delay of 1 second the current position is again logged.

I expected there to also be a stream of events being fired between when the
user stops dragging and the viewer reaching the endposition. But there is a
large gap in between these moments.

Is there any way listen for changes in this timeframe?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/marzipano/issues/313>, or unsubscribe

**Comment by b-strauss** [comment]
@campmdabt thanks, this is indeed working! 😃 

I was not aware that the `change` event includes view param changes.

cheers!
