### ISSUE TITLE
how to add hotspotcontainers in different scenes

### ISSUE THREAD

**Issue by angelatenshi** [google/marzipano#359]
hello i have a question. how do i put another hotspot container to another scene? 

I'd like to put my embedded hotspot of youtube streaming in my activity hall scene. thank you so much
![image](https://user-images.githubusercontent.com/25645599/99523176-aa7aa480-29d1-11eb-85dd-fbef08c4bdfa.png)

**Comment by mjut** [comment]
I am curious too. I am trying to modify my multiple scenes layout – generated with the "Marzipano Tool".
Trying to integrate different hotspots like shown in the demo "Hotspot Styles". I understand that I can load the html of the hotspots into my file. I know how to call the js and the css. But how do I tell differnet hotspots in what scene to apply?

Thanks for pointing out any suggestions!

**Comment by Maurice94** [comment]
I was wondering the exact same thing. When I followed the code of the demo (embedded hotspot) it would just show the video in the last scene and kept overwriting it in the previous ones.
So I found a solution that for sure isnt the most elegant way, but it works. Since I couldnt add any fields in the data.js I added sth inside of the loop in the index.js

![1](https://user-images.githubusercontent.com/58122010/101006678-81c1e580-3561-11eb-9bab-7b23b1cf1d23.PNG)
![2](https://user-images.githubusercontent.com/58122010/101006715-84243f80-3561-11eb-8111-8f929fda9d19.PNG)

**Comment by tjgq** [comment]
It's not possible to add embedded hotspots by modifying the generated `data.js` file. You must edit the JavaScript code as shown in the previous comment.

**Comment by mendozalz** [comment]
> No es posible agregar puntos de acceso incrustados modificando el generado `data.js`archivo. Debe editar el código JavaScript como se muestra en el comentario anterior.

Creo que estas equivocado, si se puede colocar Hotspots en cada escena dentro de data.js sin que estas aparezcan o interrumpan otra escena, incluso hay maneras de calcular donde colocar cada hostpot, aqui les dejo mi repo de pruebas.

https://github.com/3P4R4/Recorrido_360
