### ISSUE TITLE
Taking advantage of rendered cube to apply transformations

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#361]
Is it possible to take advantage of the rendered 3D space to appply transformations of hotspots accordingly?
For example, having ground hotspots rendered in regard to distance like so:
![image](https://user-images.githubusercontent.com/32031745/102935095-bca2a380-44a5-11eb-9fd5-80f418c7985f.png)

**Comment by tjgq** [comment]
There's support for applying an arbitrary 3D transform to a hotspot (the `perspective` options object to the `Hotspot` constructor), but Marzipano can't help you calculate the appropriate transform, since it has no understanding of the physical (real-world) geometry underlying the image.

**Comment by campmdabt** [comment]
I'm expecting it not to be within your scope since it seems like active feature development is minimal, but my understanding of the following in terms of effort is thin; I would love to be able to project a pano onto provided geometry to achieve the above effect (like with KRpano at https://krpano.com/examples/?depthmap). Is this something that you/Google would consider ever implementing?

PS this is not supposed to come across as an insult or frustration wrt active development. I appreciate this library so much more than closed source, non-standard XML implementations of an arbitrary scripting language.

**Comment by jordyno** [comment]
@tjgq my idea was to get only approximate transforms. The above example is from kuula and I don't expect this to be based on real world geometry either. I guess Marzipano knows the necessary transforms within the cube projection - for example we could assume the hotspots lie at a pre-defined height on the bottom cubeface and transform them accordingly?

**Comment by tjgq** [comment]
Unfortunately, nobody at Google is actively working on Marzipano, myself included. I can put in some time to investigate/fix bugs and review pull requests, but major feature work would have to come from external contributions.

I think there are _two_ potential features (related to scene geometry) being discussed in this thread:

**Positioning hotspots.** This can range from a simple assumed geometry (e.g. a fixed ground plane as suggested by @jordyno) or a full-blown depth map. Either way, this is just 3D geometry calculations, and the way Marzipano renders scenes doesn't need to change. (I don't think any of the existing code helps either, since Marzipano currently has no concept of a ground plane, or depth in a physical sense.)

**Scene transitions.** This is the ability to transition seamlessly between scenes, by using the depth map to interpolate the view between them (as in the krpano demo mentioned by @campmdabt). This would require changes to how Marzipano renders scenes.

**Comment by jordyno** [comment]
@tjgq correct, I am in the first feature group, which should not be too difficult to implement. I am thinking that there should be a way to do the transforms on the ground plane in a similar fashion as shown in the embedded hotspots demo with the iframe transformation - in that case it's the front facing plane. My understanding is that it can be done using extra transforms and perspective radius somehow at this point of code in the demo: https://github.com/google/marzipano/blob/c9a847e090876bf361a8397349aa8b49aefdec43/demos/embedded-hotspots/index.js#L55
What I am looking into is doing these transforms without as little guesswork as possible.

**Comment by campmdabt** [comment]
@tjgq I misunderstood what Jordy was looking for in the original ask, so I'll keep that thread out of this specific git issue to keep it clean. Thanks for the info about development!

**Comment by jordyno** [comment]
@campmdabt using the depthmap would surely be the best way to do it and also a welcome addition to Marzipano, but that seems too much work. Unless someone with skills and motivation joins :)

**Comment by jordyno** [comment]
@tjgq I got it almost figured out, all I need is an formula, which doesn't need to be super precise, to calculate the estimated perspective radius for each hotspot within "assumed space". 
I've built a simple illustrative demo of my intentions:
![image](https://user-images.githubusercontent.com/32031745/103383242-572c6380-4af2-11eb-87f0-f8ec2f1e0d07.png)
calculating extraTransforms was fairly simple, but finding a formula for the perspective.radius is beyond my miserable math knowledge. Any ideas here?
In the demo above I am using fixed 'assumed' values for radius based on pitch:
pitch....radius
0.15.....1900
0.2.......1400
0.5.......550
0.785..365
1.0.......305
1.57....260

**Comment by campmdabt** [comment]
@jordyno I threw together this spreadsheet to give you a few starting points, assuming I understand correctly that you're looking to get radius for a given pitch.

The first chart compares them directly to get a power distribution y=326.4x^(-0.891). The second chart uses the inverse of the radius (1/radius) to get a much closer approximation using a 2nd order polynomial y=-0.0015x^2+0.0049x-0.0002, but there are very few significant figures in those coefficients, so in the 3rd chart I multiplied all the 1/radius values by 1000, so (1/radius)*1000, to give you more sig figs, y=-1.4843x^2+4.9218x-0.2086. After calculating the y value, just divide by 1000 then take the inverse and you should have your radius.

Hope that helps!

[Marzipano.xlsx](https://github.com/google/marzipano/files/5771184/Marzipano.xlsx)

**Comment by jordyno** [comment]
@campmdabt thank you! I tried some curve fitting already and came up with a silly equation of `Math.roundTo((200 + (26571 - 200)/(1 + (coords.pitch/0.0241)^1.447)) - 300, 6)`
This worked approx fine. Today I gave it a second though, made a simple drawing and realized it's just a dead simple right angle triangle!!! :D
So the solution is as simple as it gets: `radius = (a / cos(α) ) * const`, where `a` is the height of the tripod and const is a proposed radius for element under the "camera" divided by tripod height.

**Comment by campmdabt** [comment]
Ah, makes perfect sense that it would mirror actual geometry if the pano is flat. I was thinking a similar thing to start, but then said "we don't have the distance to that point, so we can't use trig..." However we DO know the angle... Thanks Marzipano!

**Comment by botxboom** [comment]
Is this discussion still open?
