### ISSUE TITLE
Hotspots can't be added to a bare layer

### ISSUE THREAD

**Issue by MunishTXL** [google/marzipano#42]
Hi,
I want to use editable layer the one showed in demo, but i want to add hostpots also. I have checked the example where hotspots are added and they are added on the scene. In case of editable we have layer not scene, so how we can add hotspots on that?

**Comment by tjgq** [comment]
Hotspots aren't supported on bare layers, only scenes.

The demo you mentioned requires the ability to display multiple images at the same time, but this isn't currently supported by the `Viewer` API. That's why the demo uses layers instead of scenes.

You might be able to achieve what you want by instantiating the `HotspotContainer` class directly and adding hotspots onto it. I haven't actually tried doing this, so YMMV.

**Comment by MunishTXL** [comment]
Hi

Thanks it works by creating object of HotspotContainer class.

Thanks
