### ISSUE TITLE
StaticImageAsset not available

### ISSUE THREAD

**Issue by yanofsky** [google/marzipano#65]
the `StaticImageAsset` class doesn't appear be be available on the `Marzipano` global in 0.5.3 was it depreciated?

**Comment by tjgq** [comment]
I think `StaticImageAsset` (as well as `FlashImageAsset`) were never part of the public exports, since they're only used internally by the `StaticImageSource` implementation. They're pretty much alive and well - it's just that they're not terribly useful on their own.

May I ask what is it you're trying to do that requires access to this class?

**Comment by yanofsky** [comment]
sorry for the slow reply

I see. I was trying to avoid a cross domain issue by loading an image from an image tag rather than relying on XHR. I ended up setting up a more permissive file server to solve.
