### ISSUE TITLE
Equirectangulars exceeding WebGL maximum texture size fail to be rendered

### ISSUE THREAD

**Issue by iwersen** [google/marzipano#66]
Hi,
I´m trying Marzipano with some 5660x2830 files but it only shows a blank screen. After resizing the photo to 3500x1750, I could see the photo normally. Nice!
The start page at http://www.marzipano.net says "Marzipano is optimized to display 360° images of any size". Have you tested with this resolution?
Thanks

**Comment by tjgq** [comment]
You're almost certainly exceeding the maximum WebGL texture size supported by your browser (equirectangular images must fit in a single texture). You should see a warning in the browser's developer console if that's the case.

If you need to display larger images, use a cubemap instead of an equirectangular image.

**Comment by iwersen** [comment]
Thanks for this info! I didn´t wonder that because this one works: http://photo-sphere-viewer.js.org. 

Probably this explains: "_... allowing very good performances on WebGL enabled systems (most recent browsers) and reasonably good performances on other systems supporting HTML Canvas_".
