### ISSUE TITLE
Not working on internet explorer

### ISSUE THREAD

**Issue by mameara** [google/marzipano#68]
All marzipano demos not working on internet explorer 10 or later, any way to make it work?

**Comment by manuelcabral** [comment]
Can you check if there is any error in the console? The demos seem to be working fine here in IE11.

**Comment by mleathem** [comment]
I find the demos work in IE online ( http://www.marzipano.net/demo ),
but working from the github demos/ files there is a rendering issue.
(I have only tested video, IE11) - video sound is OK, but no image to the video.

- Console complains:

> WARNING:   Temporarily switching to software rendering to display WebGL content.
> ERROR: SecurityError  ... from marzipano.js  
as far as I can debug this related to the **bindTexture**  **TEXTURE_2D** ??
of the following code section (marzipano.js) :

`				if (o !== this._timestamp) {
					var s = e.element(),
						a = e.width(),
						l = e.height();
					if (a !== this._width || l !== this._height) {
						var h = r.maxTextureSize();
						if (a > h) throw new Error("Texture width larger than max size (" + a + " vs. " + h + ")");
						if (l > h) throw new Error("Texture height larger than max size (" + l + " vs. " + h + ")");
						this._texture && n.deleteTexture(i), i = this._texture = n.createTexture(), n.bindTexture(n.TEXTURE_2D, i), n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL, !0), n.texImage2D(n.TEXTURE_2D, 0, n.RGBA, n.RGBA, n.UNSIGNED_BYTE, s)
					} else i = this._texture, n.bindTexture(n.TEXTURE_2D, i), n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL, !0), r._useTexSubImage2D ? n.texSubImage2D(n.TEXTURE_2D, 0, 0, 0, n.RGBA, n.UNSIGNED_BYTE, s) : n.texImage2D(n.TEXTURE_2D, 0, n.RGBA, n.RGBA, n.UNSIGNED_BYTE, s);
					r._generateMipmaps ? (n.texParameteri(n.TEXTURE_2D, n.TEXTURE_MAG_FILTER, n.LINEAR), n.texParameteri(n.TEXTURE_2D, n.TEXTURE_MIN_FILTER, n.LINEAR_MIPMAP_LINEAR), n.generateMipmap(n.TEXTURE_2D)) : (n.texParameteri(n.TEXTURE_2D, n.TEXTURE_MAG_FILTER, n.LINEAR), n.texParameteri(n.TEXTURE_2D, n.TEXTURE_MIN_FILTER, n.LINEAR)), n.texParameteri(n.TEXTURE_2D, n.TEXTURE_WRAP_S, n.CLAMP_TO_EDGE), n.texParameteri(n.TEXTURE_2D, n.TEXTURE_WRAP_T, n.CLAMP_TO_EDGE), n.bindTexture(n.TEXTURE_2D, null), this._timestamp = o, this._width = a, this._height = l
				}`

- Since this DOES work on http://www.marzipano.net/demo and I've tried to get this working locally using the same saved files and it doesnt, (same issue sound only) - my other hunch is that there's must be some other server configuration difference (e.g. .htaccess  - Encoding-Type ) ?

**Comment by tjgq** [comment]
SecurityError usually means a CORS issue (https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).

IE 10 and 11 disallow cross-domain videos from being rendered on WebGL (http://connect.microsoft.com/IE/feedbackdetail/view/967946/support-crossorigin-cors-for-drawing-video-to-canvas-both-2d-and-webgl). Note that even though you copied the demo files locally, the video is still loaded from www.marzipano.net.

To make the demo work locally, you need to also serve the video from your local webserver.
