### ISSUE TITLE
Progressive loading of multires tiles?

### ISSUE THREAD

**Issue by pohnean** [google/marzipano#99]
Hi,
Can marzipano be configured to load multires tiles progressively from lower levels to higher levels?

Right now it seems like it just loads the tiles of the same level.

**Comment by tjgq** [comment]
Yes, this is possible. See [this demo](http://www.marzipano.net/demos/cube-multi-res/index.html) (source code [here](https://github.com/google/marzipano/blob/master/demos/cube-multi-res)) for an example.

**Comment by pohnean** [comment]
I think you misunderstand. I know marzipano can do multires. But it's multires implementation seems to only load the tiles of the zoom level only.

For example, consider the screenshot attached. It was initially zoomed out (level 1 was loaded), then zoomed in to level 5. As you pan right, only tiles from level 5 start to load. Progressive loading would mean visible tiles from level 4,3,2 are also loaded. This is done so that the image doesnt go from very blurry, to sharp all of a sudden, but progressively gets sharper as the higher level tiles are loaded. This method would use more bandwidth, but gives a better experience, in my opinion.

As a reference, KRpano has this option: https://krpano.com/docu/xml/?version=10814

![screen shot 2017-09-05 at 9 55 31 am](https://user-images.githubusercontent.com/846343/30041991-d8f38f44-9220-11e7-8327-375996cbdec8.png)

**Comment by tjgq** [comment]
Sorry, I misunderstood. What you describe isn't currently possible. Marzipano always loads tiles at the most appropriate resolution level for the current view. While they are loading, it falls back to other available tiles (these may be either pinned tiles, as is usually the case with the first level, or tiles that have recently been displayed).

**Comment by mjau-mjau** [comment]
Replying to an old post, I know, but it seems this issue is still very valid and nothing changed. We recently integrated a FLAT Marzipano-based panorama viewer into our gallery solution [[see demo]](https://demo.photo.gallery/examples/plugins/panorama/). Many of our clients are using our plugin for projects originally exported from Pano2VR and Krpano, and essentially everything is working fine. However, as highlighted by one of our clients, there is quite a huge difference in the perceptive speed difference between Pano2VR and Marzipano. For detail about the differences, you can see our forum post:
https://forum.photo.gallery/viewtopic.php?f=63&t=9709&start=15

Out client also created a Youtube video that highlights the differences between the SAME project running from 1) X3 / Marzipano, and 2) Pano2VR. See for yourself:
https://www.youtube.com/watch?v=hBrUztJZcvc&feature=youtu.be

You can compare the two identical exports here:
https://portfolio.voyezvousca.fr/portfolio/panorama/#pano=lama (Marzipano)
https://portfolio.voyezvousca.fr/demo/ (Pano2VR)

Essentially, there are TWO major differences that make Marzipano "seem" slower:

1) Marzipano seems to have an unreasonably low LRU cache / `previouslyVisibleCacheSize`, as noted in this topic #110 
2) Marzipano does not have any native logic about loading levels progressively as noted in this original post. By default, you might pin level 1, but that is often ultra-low resolution, and combined with the incredibly low LRU cache, it means you will constantly see "ugly square low-res cubes" while navigating the panorama.

For actual visitors, the combination of the two factors above, seems to make Marzipano much less appealing, and seems way too biased towards low-memory low-bandwidth devices.

We already remedied the issue by auto-pinning TWO levels (0-1) for flat panoramas, which makes sure level 1 is always loaded and pinned as fallback. This is an improvement, but not a solution of course. I would also be looking into increasing the `previouslyVisibleCacheSize`, although I am currently not quite sure how to do it after normal `Marzipano.FlatView()` initialization. This option should be more accessible?

Surely it should be time to consider increasing the default LRU cache? I know you can't detect memory availability per device, but you could use screen/max_texture_size to make an estimation and at least increase the LRU cache on desktop devices. I see Pano2VR must utilize a cache that is either unlimited, or something several dimensions larger than the Marzipano LRU cache.

Thanks!

**Comment by tjgq** [comment]
Sorry for the delayed response - I wanted to have something concrete to share before getting back to you.

I agree that progressive loading is a desirable improvement, especially for gigapixel panos. I've implemented a proof of concept (code [here](https://github.com/tjgq/marzipano/tree/progressive), demo [here](https://tjgq.github.io/progressive-demo/)). I see a significant improvement compared to the current version, but I was hoping you'd give it a spin and let me know what you think.

The code isn't quite ready for prime time yet. It needs a couple of performance improvements, and we need to decide whether to still support the old, non-progressive mode; if so, I need to work it back in. This is something I can do once I'm sure the PoC meets the goals.

I would also like to comment on your other points.

I agree that the LRU size is ridiculously small by today's hardware standards; a single 512x512 texture in RGBA format is just 1MB. However, note that multiple TextureStores may hold textures at the same time (e.g,. multi-layer scenes) so we do want to be careful. I've increased it to 512 in the demo above, but we can probably go even higher.

This brings up a related problem: visible/pinned tiles do not count towards the limit, so the LRU size is on top of however many visible/pinned tiles you already have (and with progressive loading, the number of "visible" tiles goes up, since parent tiles are effectively pinned). I'd like to make the limit global, and  also do the accounting in terms of memory instead of number of tiles (since obviously tile size affects memory usage). I've opened #221 for this.

Finally, with regards to setting the `previouslyVisibleCacheSize` option: we can surface it higher up in the API (say, at the Scene level), but I disagree about adding a way to change it after initialization: the amount of installed memory is fixed, so it should be possible to come up with an adequate value for the device and initialize it once.

**Comment by mjau-mjau** [comment]
Sorry for the late reply Tiago.

> I agree that progressive loading is a desirable improvement, especially for gigapixel panos. I've implemented a proof of concept (code [here](https://github.com/tjgq/marzipano/tree/progressive), demo [here](https://tjgq.github.io/progressive-demo/)). I see a significant improvement compared to the current version, but I was hoping you'd give it a spin and let me know what you think.

Yes, there seems to be a significant improvement when navigating the panorama. I assume I am seeing some progressive level loading mechanism, as well as increased LRU size?

Tested on **iPhone**, the new demo seems to be able to entirely cache 360 degrees of tiles in default loaded view. This looks great compared to the existing demo, which show blurry loading tiles on movement in any direction.

Tested on **4K display**, the new demo seems to be able to cache approximately 180 degrees of rotation in default loaded view. This offers much higher movement threshold without having to re-load tiles. When re-loading of tiles does occur, it also looks much smoother because of progressively loaded levels.

All in all, seems like a great improvement. From the perspective of high-end users on large displays, I am sure they would want even higher LRU size, but that would require some Marzipano to make guesses based on device capabilities (texture_size, screen, browser, OS, etc). Unlikely, although it could be applied from options perhaps.

> The code isn't quite ready for prime time yet. It needs a couple of performance improvements, and we need to decide whether to still support the old, non-progressive mode; if so, I need to work it back in. This is something I can do once I'm sure the PoC meets the goals.

From my non-expert perspective, I would say no. I can't imagine any scenario where anyone would want to revert to an inferior mode which simply doesn't have any feasible advantages. Panorama viewing is high-end and should emphasize towards user view quality, at the potential cost of slightly increased bandwidth and memory usage.

> I agree that the LRU size is ridiculously small by today's hardware standards; a single 512x512 texture in RGBA format is just 1MB. However, note that multiple TextureStores may hold textures at the same time (e.g,. multi-layer scenes) so we do want to be careful. I've increased it to 512 in the demo above, but we can probably go even higher.

Understood. LRU is per scene? When navigating to a new scene, aren't non-pinned tiles evicted from the closed scene? Realistically, I can only see this being a problem if the developer is over-pinning and/or there are just too many scenes.

> This brings up a related problem: visible/pinned tiles do not count towards the limit, so the LRU size is on top of however many visible/pinned tiles you already have (and with progressive loading, the number of "visible" tiles goes up, since parent tiles are effectively pinned). I'd like to make the limit global, and also do the accounting in terms of memory instead of number of tiles (since obviously tile size affects memory usage). I've opened #221 for this.

Makes sense.

> Finally, with regards to setting the `previouslyVisibleCacheSize` option: we can surface it higher up in the API (say, at the Scene level), but I disagree about adding a way to change it after initialization: the amount of installed memory is fixed, so it should be possible to come up with an adequate value for the device and initialize it once.

Yes. No I don't think it needs to be set after initialization, but it would be useful as an accessible pre-init option.

Thanks again!

**Comment by tjgq** [comment]
> Yes, there seems to be a significant improvement when navigating the panorama. I assume I am seeing some progressive level loading mechanism, as well as increased LRU size?

The demo I linked to is an implementation of progressive loading, with an LRU size of 512. I haven't had time to work on it further; I will try to get it submitted later in the week.

> Tested on iPhone, the new demo seems to be able to entirely cache 360 degrees of tiles in default loaded view. This looks great compared to the existing demo, which show blurry loading tiles on movement in any direction.
>
> Tested on 4K display, the new demo seems to be able to cache approximately 180 degrees of rotation in default loaded view. This offers much higher movement threshold without having to re-load tiles. When re-loading of tiles does occur, it also looks much smoother because of progressively loaded levels.

Maybe you're doing this already, but if your intention is to cache as much of the panorama as possible, make sure that you're setting your `Cache-Control` headers correctly so that the browser doesn't download the same image multiple times. The browser cache can grow significantly larger than the available memory, and reloading from cache should be a lot faster than re-downloading.

> Understood. LRU is per scene? When navigating to a new scene, aren't non-pinned tiles evicted from the closed scene? Realistically, I can only see this being a problem if the developer is over-pinning and/or there are just too many scenes.

Yes, usually there will be a single visible layer (thus a single active LRU) at a time. The exception is scenes with multiple layers (e.g. a semitransparent layer overlaid on top of another), or someone not using the Viewer API and doing their own cache management. But that's not the common use case, and we don't need to worry too much about it.

**Comment by mjau-mjau** [comment]
Good job!

> make sure that you're setting your Cache-Control

Always. The visual effects of reloading browser-cached tiles is still unsatisfactory.

Tiago, can I send you a private email? My email is karl at photo.gallery.

**Comment by tjgq** [comment]
This has now been implemented. In the interest of simplicity, I haven't added an option to turn progressive loading off. I can add it back if there's enough demand.

**Comment by pohnean** [comment]
Awesome job guys! Glad this made it in!

**Comment by calbear47** [comment]
@mjau-mjau Hi there! 

The demo you provided above [[here](https://demo.photo.gallery/examples/plugins/panorama/#pano=salle-des-fetes)], I have two questions on how you implemented that. 

1. How did you load low res single equirectangle image first? Are those two different layers?
2. I noticed that once the full image loads, it's zoomed all the way out. How did you achieve that? I'm dealing with equirectangle images, but they always load by being zoomed all the way in. 

Any code examples from those demos you link would be amazing, but I understand that might not be possible.
